### ISSUE TITLE
Suggestion: Times-Series Return Types

### ISSUE THREAD

**Issue by orcu** [etaymaz/CBRT#1]
Veriler su anda data frame olarak donuluyor. Default donulen degerin bir xts veya zoo nesnesi olmasi nasil olur?
```
# Current CBRT usage
usdtry_df = getDataSeries("TP.DK.USD.S.EF.YTL", CBRTKey = tcmb_key, freq = 5, startDate = "01-01-1990", endDate="04-04-2020", na.rm = T)
usdtry = xts(usdtry_df$TP.DK.USD.S.EF.YTL, usdtry_df$time)
colnames(usdtry) = colnames(usdtry_df)[2]

# Current quantmod usage
cpi = getSymbols("TURCPIALLMINMEI", source="FRED", auto.assign = FALSE)
```
Bu arada guzel bir R-package. CRAN'de de bulunmasini umit ederim. Tesekkurler.

**Comment by etaymaz** [comment]
Zaman değişkeninin formatı kullanıcı tercihine göre değişebiliyor, bu nedenle genel bir format tercih ettik, yıllık veride "numeric", diğer verilerde (günlük, aylık, vb) "date" olarak. Bu bağlı paket sayısının da az olmasını sağlıyor. Fakat yeni versiyonlarda bu bir opsiyon olarak sunulabilir.
